services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greenforce-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
    networks:
      - greenforce-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greenforce-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    networks:
      - greenforce-net

networks:
  greenforce-net:
    driver: bridge
